# AlphaPunch Configuration File

# Directory paths
directories:
  output: 'output'
  database: 'database'
  download: 'downloads'
  plots: 'plots'
  reports: 'reports'

# Core algorithm parameters
algorithm:
  fingerprint_size: [64, 64]
  input_shape: [256, 256, 3]
  embed_strength: 0.4
  similarity_threshold: 0.65

  # Feature weights for different domains
  feature_weights:
    vgg: 0.4
    wavelet: 0.3
    dct: 0.3

  # Wavelet configuration
  wavelet:
    type: 'db4'
    level: 3
    detail_weight: 0.5

  # Error correction
  error_correction:
    enabled: true
    gaussian_kernel_size: 3
    gaussian_sigma: 0.5

  # Neural attention parameters
  neural_attention:
    enabled: true
    attention_layers: 3
    max_memory_gb: 16
    use_cpu_fallback: true
    block_size: 64
    base_filters: 64
    attention_dropout: 0.1
    feature_channels: 256
    learning_rate: 0.001
    batch_size: 32
    training_epochs: 20
    attention_weights:
      spatial: 0.4
      channel: 0.3
      position: 0.3
    post_processing:
      enabled: true
      clahe_clip_limit: 2.0
      clahe_grid_size: [8, 8]

# Verification parameters
verification:
  stage_weights: [0.3, 0.3, 0.2, 0.2]
  min_confidence: 0.75
  modification_thresholds:
    jpeg_quality: 0.4
    geometric: 0.25
    intensity: 0.15

# Testing configuration
testing:
  random_seed: 42
  num_original_images: 100
  num_unrelated_images: 20
  cross_validation:
    enabled: true
    num_folds: 5
    validation_split: 0.2

  # Manipulation parameters for testing
  manipulations:
    blur_kernel: 5
    jpeg_quality: 75
    rotation_angle: 5
    crop_percent: 10
    resize_factor: 0.5
    noise_std: 10

# Training parameters
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
  optimizer:
    type: 'adam'
    beta1: 0.9
    beta2: 0.999
    epsilon: 1e-8
  loss_weights:
    embedding: 0.6
    verification: 0.4

# Logging configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s.%(funcName)s - %(message)s'
  file_handler:
    enabled: true
    max_bytes: 10485760  # 10MB
    backup_count: 5
  console_handler:
    enabled: true
  propagate: true

# Visualization settings
visualization:
  dpi: 300
  figure_size: [10, 6]
  plot_formats: ['png', 'pdf']
  colors:
    success: '#2ecc71'
    failure: '#e74c3c'
    neutral: '#3498db'
  attention_maps:
    enabled: true
    colormap: 'viridis'
    alpha: 0.7

# Performance monitoring
performance:
  memory_tracking: true
  timing_enabled: true
  profiling:
    enabled: false
    output_dir: 'profiling'

# API settings (credentials loaded from .env)
unsplash: {}  # Credentials loaded from environment variables

# Security settings
security:
  hash_algorithm: 'sha256'
  key_iterations: 100000
  salt_size: 32

# System resources
resources:
  num_workers: 4
  gpu_memory_limit: 0.8  # 80% of available GPU memory
  cpu_threads: -1  # Use all available threads
  temp_dir: 'tmp'

# Cache settings
cache:
  enabled: true
  max_size: 1024  # MB
  ttl: 3600  # seconds
  directory: 'cache'
