# NeuralMark Configuration File

# Algorithm Selection
algorithm_selection:
  type: 'cdha'  # Options: 'amdf', 'cdha'
  enable_comparison: false  # Enable running both algorithms for comparison

# Directory paths
directories:
  base_output: 'output'  # Base directory for all run outputs
  downloads: 'downloads' # Stays at base
  logs: 'logs'          # Stays at base
  database: 'database'  # Stays at base if it's not run-specific

# Cleanup configuration
cleanup:
  enabled: false       # Whether to run cleanup at all
  pre_run: false       # Whether to cleanup before run
  post_run: false     # Whether to cleanup after run
  preserve_runs: 5    # Number of previous runs to preserve

# Core algorithm parameters
algorithm:
  fingerprint_size: [32, 32] # Reduce from 64x64
  input_shape: [123, 128, 3] # Reduce from 256x256
  resize_interpolation: 'LINEAR'  # Options: LINEAR, CUBIC, NEAREST
  embed_strength: 1.2
  similarity_threshold: 0.35
  attack_threshold: 0.5

  # AMDF specific parameters
  amdf:
    feature_weights:
      vgg: 0.3
      wavelet: 0.5
      dct: 0.2
    neural_attention:
      enabled: true
      attention_layers: 3
      base_filters: 64
      feature_channels: 256

  # Neural attention settings
  neural_attention:
    enabled: true
    feature_channels: 128 # Reduce from 256
    num_heads: 4 # Reduce from 8
    num_attack_types: 5

  # CDHA specific parameters
  cdha:
    feature_weights:
      spatial: 0.4
      frequency: 0.3
      wavelet: 0.3
    attention:
      num_heads: 8
      key_dim: 64
      num_attack_types: 5
    hierarchical:
      low_dim: 64
      mid_dim: 128
      high_dim: 256

  # Testing parameters
  verification:
    stage_weights: [0.4, 0.3, 0.2, 0.1]
    min_similarity: 0.45

# Testing configuration
testing:
  random_seed: 42
  total_images: 50
  train_ratio: 0.6

  cross_validation:
    enabled: true
    num_folds: 5
    validation_split: 0.2

  # Manipulation parameters
  manipulations:
    blur:
      kernel_size: 3
      sigma: 0.5
    compress:
      quality: 85
    rotate:
      angle: 2
    crop:
      percent: 5
    resize:
      factor: 0.8
    noise:
      std: 5

  # Test metrics
  metrics:
    min_accuracy: 0.9
    max_false_positive: 0.01
    max_false_negative: 0.1

resources:
  num_workers: 1 # Set to 1 for sequential processing
  batch_size: 1
  gpu_enabled: false
  memory_limit: 0.4
  parallel_processing: false  # Add flag to control parallelism

performance:
  enable_caching: true
  cache_dir: 'cache'
  optimization_level: 'high'

# Logging configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: true
  console: true

# API settings
unsplash: {}  # Credentials loaded from environment variables