# AlphaPunch Configuration File

# Directory paths
directories:
  output: 'output'
  database: 'database'
  download: 'downloads'
  plots: 'plots'
  reports: 'reports'
  fingerprinted: 'fingerprinted'
  manipulated: 'manipulated'
  test: 'test'

# Core algorithm parameters
algorithm:
  fingerprint_size: [64, 64]
  input_shape: [256, 256, 3]
  resize_interpolation: 'LINEAR'  # Options: LINEAR, CUBIC, NEAREST
  embed_strength: 0.4
  similarity_threshold: 0.65

  feature_weights:
    vgg: 0.4
    wavelet: 0.3
    dct: 0.3

  neural_attention:
    enabled: true
    attention_layers: 3
    base_filters: 64
    feature_channels: 256

# Testing configuration
testing:
  random_seed: 42
  total_images: 100      # Total number of images to use
  train_ratio: 0.8       # 80% for training/fingerprinting

  cross_validation:
    enabled: true
    num_folds: 5
    validation_split: 0.2

  # Manipulation parameters for testing
  manipulations:
    blur:
      kernel_size: 5
      sigma: 1.0
    compress:
      quality: 75
    rotate:
      angle: 5
    crop:
      percent: 10
    resize:
      factor: 0.5
    noise:
      std: 10

  # Verification thresholds
  thresholds:
    base: 0.65          # Base similarity threshold
    manipulated: 0.55   # Threshold for manipulated images

  # Test metrics
  metrics:
    min_accuracy: 0.9
    max_false_positive: 0.01
    max_false_negative: 0.1

# Logging configuration
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: true
  console: true

# API settings (credentials loaded from .env)
unsplash: {}  # Credentials loaded from environment variables
